In [1]:
import numpy as np

In [3]:
a=np.array([])
b=np.array([1,2,55,23,5,21])
c=np.array([[123,5536,32],[14,13,22]])

In [4]:
a

array([], dtype=float64)

In [7]:
type(a)

numpy.ndarray

In [5]:
b

array([ 1,  2, 55, 23,  5, 21])

In [8]:
type(b)

numpy.ndarray

In [12]:
b.ndimc

1

In [15]:
b.size

6

In [6]:
c

array([[ 123, 5536,   32],
       [  14,   13,   22]])

In [9]:
type(c)

numpy.ndarray

In [11]:
c.ndim

2

In [13]:
c.size

6

In [2]:
n=np.array([[2,4,6,2],[24,34,56,32],[100,400,500,700]])

NameError: name 'np' is not defined

In [3]:
import numpy as np 

In [4]:
n=np.array([[2,4,6,2],[24,34,56,32],[100,400,500,700]])

In [5]:
n

array([[  2,   4,   6,   2],
       [ 24,  34,  56,  32],
       [100, 400, 500, 700]])

In [6]:
n[0][0]

2

In [7]:
n[0,0]

2

In [8]:
n[1,2]

56

In [9]:
n[2,[0,1]]

array([100, 400])

In [15]:
n[2,1:3]

array([400, 500])

In [20]:
n[1:,2:]

array([[ 56,  32],
       [500, 700]])

In [21]:
n[1:3]

array([[ 24,  34,  56,  32],
       [100, 400, 500, 700]])

In [22]:
n[1,:2]

array([24, 34])

In [25]:
n[0:3,3]

array([  2,  32, 700])

a range

In [26]:
list(range(5,51))

[5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50]

In [28]:
np.arange(5,51)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [29]:
np.arange(5.5,50.3)

array([ 5.5,  6.5,  7.5,  8.5,  9.5, 10.5, 11.5, 12.5, 13.5, 14.5, 15.5,
       16.5, 17.5, 18.5, 19.5, 20.5, 21.5, 22.5, 23.5, 24.5, 25.5, 26.5,
       27.5, 28.5, 29.5, 30.5, 31.5, 32.5, 33.5, 34.5, 35.5, 36.5, 37.5,
       38.5, 39.5, 40.5, 41.5, 42.5, 43.5, 44.5, 45.5, 46.5, 47.5, 48.5,
       49.5])

#Reshape

In [31]:
np.sqrt(81)

9.0

In [32]:
n.max()

700

In [33]:
n

array([[  2,   4,   6,   2],
       [ 24,  34,  56,  32],
       [100, 400, 500, 700]])

In [35]:
n.argmax()

11

In [36]:
n.argmin()

0

In [37]:
n/2

array([[  1.,   2.,   3.,   1.],
       [ 12.,  17.,  28.,  16.],
       [ 50., 200., 250., 350.]])

In [38]:
n/2

array([[  1.,   2.,   3.,   1.],
       [ 12.,  17.,  28.,  16.],
       [ 50., 200., 250., 350.]])

In [39]:
n/4

array([[  0.5,   1. ,   1.5,   0.5],
       [  6. ,   8.5,  14. ,   8. ],
       [ 25. , 100. , 125. , 175. ]])

# Random

In [40]:
np.random.rand(2,3)

array([[0.15895783, 0.11303952, 0.24691506],
       [0.50112896, 0.97024411, 0.30429556]])

In [42]:
np.random.randn(2,2)

array([[ 0.23824737,  0.80517078],
       [-0.32082586, -0.1072074 ]])

In [48]:
s=np.random.randint(9,90,12).reshape(4,3)

In [49]:
s

array([[77, 65, 15],
       [12, 83,  9],
       [16, 26, 72],
       [87, 33, 33]])

In [51]:
s.sum()

528

In [52]:
s.sum(axis=1)

array([157, 104, 114, 153])

In [53]:
s.sum(axis=0)

array([192, 207, 129])

# 3d

In [54]:
d=np.array([[[4,40],[5,50],[6,60]],[[7,70],[8,80],[9,90]],[[5,55],[4,44],[6,66]]]) 

In [55]:
d.shape

(3, 3, 2)

# NAN- not a number

In [56]:
x = np.array([12,56,np.nan,66,100,np.nan])

In [57]:
x

array([ 12.,  56.,  nan,  66., 100.,  nan])

In [58]:
x.dtype

dtype('float64')